[package]
name = "rust-proj"
version = "0.1.0"
authors = ["Ujjwal Kumar <31813384+Ujjwal0501@users.noreply.github.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"